name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: rationapp.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t rationapp.azurecr.io/ration-app:${{ github.sha }} .
        docker push rationapp.azurecr.io/ration-app:${{ github.sha }}
        docker tag rationapp.azurecr.io/ration-app:${{ github.sha }} rationapp.azurecr.io/ration-app:latest
        docker push rationapp.azurecr.io/ration-app:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Set AKS context
      uses: azure/aks-set-context@v3
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
        resource-group: ${{ secrets.AKS_RESOURCE_GROUP }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl set image deployment/ration-app ration-app=rationapp.azurecr.io/ration-app:${{ github.sha }}

    - name: Wait for deployment
      run: kubectl wait --for=condition=available --timeout=300s deployment/ration-app

    - name: Verify deployment
      run: |
        kubectl get pods
        kubectl get svc
